// Multi-subreddit Reddit bot — samples from a list, posts freshest unseen items.

import { type Api, redditBot } from "../bots.ts";

const SUBREDDITS = [
  "me_irl",
  "okbuddyretard",
  "comedyheaven",
  "woahdude",
  "nextfuckinglevel",
  "wholesomememes",
  "wizardposting",
  "gifs",
  "WritingPrompts",
  "aww",
  "DIY",
  "books",
  "science",
  "wallstreetbets",
  "PrequelMemes",
  "math",
  "Documentaries",
  "Advice",
  "DesignPorn",
  "Design",
  "memes_of_the_dank",
  "gamephysics",
  "madlads",
  "perfectlycutscreams",
  "softwaregore",
  "teenagers",
  "BoneHurtingJuice",
  "the_pack",
  "youtubehaiku",
  "tiltshift",
  "Ooer",
  "emojipasta",
  "surrealmemes",
  "AlbumArtPorn",
  "graphic_design",
  "heavymind",
  "Illustration",
  "fashion",
];

export default (api: Api) => redditBot(api, { subs: SUBREDDITS, sample: 12, maxPosts: 3 });
